### ISSUE TITLE
Lock Ratio - the hands seem to become askew of the tick marks

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#209]
There may be an open issue for this? I just noticed when I used Lock Ratio with no tick marks and then activated the tick marks, the hands were askew of the marks. Mathematically they might be in challenge ratio, but visually it seems a bit off. And describing between the tick marks is more wordy, so I am concerned this may become an issue for the described experience.

We haven't designed the Responses yet for when Lock Ratio is on, though I was hoping the Both Hands responses would get us started.

It's a 1:2 ratio here in this screen shot
![Screen Shot 2020-10-14 at 2 51 03 PM](https://user-images.githubusercontent.com/1902116/96023664-55290180-0e2d-11eb-9009-724ab01b8b75.png)

This is an issue from a described experience because describing in between the tick marks can be more wordy.

**Comment by terracoda** [comment]
Keep an eye out for a repeat of this as this is not a 1:2 ratio. Not sure if it is a model bug or a visual bug.

**Comment by zepumph** [comment]
@terracoda said that likely it was happening while she was using the screen reader. 

@emily-phet said to not spend too much time trying to reproduce. We can always give this to QA to try to reproduce.

**Comment by zepumph** [comment]
I haven't found this in the last month. I think it would be best to link this issue in the first dev test we have for the sim.

**Comment by terracoda** [comment]
Now that we have lock ratio responses, I can have a look at this sim with this issue in mind, and I like the idea f linking this issue to a dev test.

**Comment by terracoda** [comment]
@zepumph, I don't know if this screen shot is related to this issue, but I wanted to put it here, just in case. I just noticed that the hands look like they are at 0 an 0.5 when they are actually reading as 0.5 and 1 and are in lock ratio.

I was flipping back and forth between No Tick Marks and Numbered Tick Marks while checking responses in the A11t View.
![Screen Shot 2020-11-23 at 11 47 52 AM](https://user-images.githubusercontent.com/1902116/99981259-bd032e00-2d83-11eb-8362-ede3bebf429d.png)

**Comment by terracoda** [comment]
Actually, this might be due to the hands starting off in the incorrect position. I just noticed that at start up on the second screen the hands are not visually starting at 2 and 4.

![Screen Shot 2020-11-23 at 2 46 30 PM](https://user-images.githubusercontent.com/1902116/99999629-014df880-2d9b-11eb-8ce2-c45ca2b7c8ac.png)

**Comment by terracoda** [comment]
I just found some funny business. It might not be related, but I think it is since I have been playing a lot with Lock Ratio, these days.
Darn, I can't reproduce it, but I think the hands went lower than their "allowed value" after I locked ratio, went all the up the screen and then allow the way back down again.

It was when I had the hands back near the bottom, the visual value was lower than than the values over in the state descriptions which were the minimum allowed values.

I thought I could reproduce it, but I can't.

**Comment by terracoda** [comment]
I don't know how I got here, but this looks funny to me:
![Screen Shot 2020-11-27 at 4 43 29 PM](https://user-images.githubusercontent.com/1902116/100481772-c8ca5980-30cf-11eb-8165-bdac66a7f133.png)

**Comment by terracoda** [comment]
It seems after this happens, the numbers in the state descriptions are off:
![Screen Shot 2020-11-27 at 4 46 36 PM](https://user-images.githubusercontent.com/1902116/100481918-3fffed80-30d0-11eb-934c-d998663ee538.png)

**Comment by terracoda** [comment]
After a reset, the hands are in the wrong place, the State Descriptions are correct.
![Screen Shot 2020-11-27 at 4 48 24 PM](https://user-images.githubusercontent.com/1902116/100481988-86ede300-30d0-11eb-932c-0b9e73bece1d.png)

**Comment by terracoda** [comment]
Oh, THIS happens after I resize the browser window!!! FOUND IT!

**To reproduce:**
1. Load sim
2. go to screen 2
3. lock hands in ratio
4. move hands so they are at the lowest possible position
5. resize the browser window
6. the left hand slips below zero, and gets stuck in the wrong place

So, when I resize the browser window, the left hand slips below the bar, and then it stays askew there after, even after a reset!

Notice the pink focus highlight is bumped down, too.

This happens in the regular view as well, not just the A11y View.
![Screen Shot 2020-11-27 at 4 57 41 PM](https://user-images.githubusercontent.com/1902116/100482390-c79a2c00-30d1-11eb-8f3c-d4e35721d283.png)

**After the reset**
![Screen Shot 2020-11-27 at 5 01 29 PM](https://user-images.githubusercontent.com/1902116/100482537-4d1ddc00-30d2-11eb-8361-88a5682afabd.png)

So glad I figured this out.
@KatieWoe, I am assigning back to @zepumph

**Comment by terracoda** [comment]
This issue could possibly be related to #251 noted by @emily-phet.
Not sure, but it took a long time for me to figure this one one out.

**Comment by zepumph** [comment]
Wow. Really great work. https://github.com/phetsims/ratio-and-proportion/issues/209#issuecomment-734983859 is awesome, and made it very easy to find the bug. This should be solved now. When I repeat your above instructions on master, the hands stay at .5 and 1. Please confirm fixed and feel free to close.

**Comment by terracoda** [comment]
We may still have an issue. I am not testing this issue yet, but I found that the description can become miss-aligned without changing the size of the window in comment https://github.com/phetsims/ratio-and-proportion/issues/245#issuecomment-742010350 and in comment https://github.com/phetsims/ratio-and-proportion/issues/245#issuecomment-742018464

**Comment by zepumph** [comment]
I think that is a separate problem. I'll make an issue.

**Comment by zepumph** [comment]
I created https://github.com/phetsims/ratio-and-proportion/issues/279.

**Comment by terracoda** [comment]
The left hand no longer slips below the bar when I resize the browser window, and thus does not become askew.
Closing.
