### ISSUE TITLE
Tick mark description says "around" when it is "on"

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#279]
From https://github.com/phetsims/ratio-and-proportion/issues/245#issuecomment-742010350, @terracoda found a bug while reviewing that issue.

Here are her posts describing it over there:

With ratio locked, it seems when the left hand is visually "on a tick mark", it described as being "around" to tick mark.

Here's 2 screen shots. Not sure if this is directly related to this issue, but since I am testing this issue, I just need to post it here before I lose my train of thought:
![Screen Shot 2020-12-09 at 4 15 54 PM](https://user-images.githubusercontent.com/1902116/101680110-cc000680-3a3a-11eb-9002-12e60fd45b0a.png)
![Screen Shot 2020-12-09 at 4 19 38 PM](https://user-images.githubusercontent.com/1902116/101680119-cefaf700-3a3a-11eb-95e5-3f1047147382.png)

Double checking with Lock Ratio unchecked.
Ok, this seems to happen only with Lock Ratio checked.

I can start out with Both Hands at 1:3 with each on the correct tick mark, but by the time the Left Hand gets to Tick Mark 2, the descriptions says "around tick mark 2" with right hand "on tick mark 6".

Also, if I start out at 1:3 and then move the hands down as far as they can go with ratio locked, and then move back up again, the left hand is described as "around tick mark 1" when it visually gets back on 1.

**Comment by terracoda** [comment]
@zepumph, I found spot where  the incorrect "around" can happen without ratio locked.

When I have 1:3 and have the Tick Mark Range set to 0 to 30, the first tick mark seems to always be described as "around first Tick Mark". 

**Screenshot with VO content**
![Screen Shot 2020-12-10 at 10 54 07 AM](https://user-images.githubusercontent.com/1902116/101784648-5ba6c300-3ad6-11eb-9861-a6ed0a8d9d97.png)

In fact, when exploring with small steps, I can't seem to get the left on a half-way tick mark or a full tick mark at all. The left hand is always describes as "around" the half or full tick mark.

![Screen Shot 2020-12-10 at 11 05 41 AM](https://user-images.githubusercontent.com/1902116/101785739-aecd4580-3ad7-11eb-89bc-b649d8105a8a.png)

Maybe some kind of rounding error?

**Comment by zepumph** [comment]
Yes, it is a rounding error. I can reproduce it consistently by moving the consequent, because then the model has to recompute what the child should be:

```
left: 0.299999, 
right: 0.9, 
distance: 0.600001, 
current ratio: 0.33333222222222225, 
target ratio: 0.3333333333333333,
unclampedFitness: 0.9999850000000006
```

I feel like this has something to do with #243. Perhaps I'm clamping too early in a case, and then it isn't able to round up to 3.

**Comment by zepumph** [comment]
This has been fixed by https://github.com/phetsims/ratio-and-proportion/commit/47ef113d62b828f14e4ed0438c49d1520161d244. @terracoda can you please confirm and feel free to close.

**Comment by terracoda** [comment]
I did a fresh pull. cleared history, and cleared caches.
I can still get "around 1", when 1:3

Steps to reproduce:
1. got create screen
2. set right number spinner to 3
3. choose numbered tick marks
4. set range to 0 to 30
5. move right hand to tick mark 3
6. move left hand to tick mark 1

I can't actually get the left hand to tick mark 1 unless the right hand is on tick mark 3.

![Screen Shot 2020-12-10 at 10 54 07 AM](https://user-images.githubusercontent.com/1902116/101955288-1cf93180-3bd8-11eb-9324-8c2af670c526.png)

**Comment by terracoda** [comment]
This happens with sliders and the both hands interactions.

**Comment by terracoda** [comment]
back over to you @zepumph.

**Comment by terracoda** [comment]
This seems to only be an issue for tick mark 1.
Subsequent steps seem to be on mark visually and in the description.
![Screen Shot 2020-12-11 at 6 38 28 PM](https://user-images.githubusercontent.com/1902116/101959551-18d11200-3be0-11eb-9585-d3f04315fe0d.png)

**Comment by terracoda** [comment]
Oh sorry, I lied. I didn't read the "around" in the previous post :-P

**Comment by terracoda** [comment]
I think it may only be an issue with range 0 to 30.

**Comment by zepumph** [comment]
@terracoda and I discussed this further today, and we see that this is because of using a shift keyboard step of 1/10 of an original tick mark, even when the range changes to 1/30. In this case, every tick mark that isn't divisible by 3 will be "around" because of the underlying math, not a rounding error. Over to @terracoda.

**Comment by zepumph** [comment]
Tagging some previous discussion about step size for range 0-30 in https://github.com/phetsims/ratio-and-proportion/issues/175 and https://github.com/phetsims/ratio-and-proportion/issues/166.

**Comment by zepumph** [comment]
Above discussion moved to https://github.com/phetsims/ratio-and-proportion/issues/298, @terracoda please review that the original bug in the first comment is fixed.

**Comment by terracoda** [comment]
@zepumph, yep this rounding issue is resolved. The left hand is now "on" the tick mark.
Thanks for explaining the difference between the issues I was finding.
<img width="494" alt="Screen Shot 2020-12-15 at 6 17 14 PM" src="https://user-images.githubusercontent.com/1902116/102276833-f56cd680-3f01-11eb-951d-3f890c0de8e1.png">
<img width="483" alt="Screen Shot 2020-12-15 at 6 16 50 PM" src="https://user-images.githubusercontent.com/1902116/102276858-04538900-3f02-11eb-927f-853e4a083c39.png">

Closing.

**Comment by terracoda** [comment]
Ok, after a reset and then explore only with the keyboard on the 0 to 30 grid, I am always on a tick mark or on a half tick mark.

When I start using the mouse to get visually aligned with a visual tick mark, I get "around".

When I start using the keyboard again, the grid snaps back to being on a tick mark or on a half tick mark.

I think the smaller grid value that we discussed yesterday has improved the situation.

In fact, when I use the mouse, I can more easily get "around" now on any grid. That might have been the case before - not sure since I didn't test with the mouse much. Now, whenever I switch back to using the keyboard, I seem to snap back onto "on" a tick mark or "on" a half tick mark.

I'm thinking things are ok now.

I'd like to see, in the description, where we transition from "around" a tick mark to "around" a half tick mark. Sometime this might seem confusing, but maybe I am trying to be too precises in an imprecise environment.

**Comment by terracoda** [comment]
oops, wrong issue.
