### ISSUE TITLE
Selection highlighting on long-press on iPad 

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#39]
I've noticed a selection box that appears when you long press on the cursors (hands) in RaP 1.0.0-dev.15 in my own testing on an iPad as well as in user interviews. This happens in Chrome and Safari. Does not happen on Microsoft Surface 10 on Chrome (though long pressing without moving the cursor enables the right-click context menu).

Pictured below:

![image](https://user-images.githubusercontent.com/47331395/81011436-356cc680-8e15-11ea-84c7-e9cbc6cd403c.png)

**Comment by zepumph** [comment]
@jessegreenberg is this similar to combo box problems in molarity? Or is it something else?

**Comment by jessegreenberg** [comment]
Not sure if it is realted to ComboBox, but looks really similar to https://github.com/phetsims/scenery/issues/1006

**Comment by jessegreenberg** [comment]
I believe it is this canvas element:
![image](https://user-images.githubusercontent.com/6396244/81024182-a2498600-8e40-11ea-85f9-e9df673f2736.png)

Probably in there for mechamarkers would be my guess? Canvas elements usually have a closing tag, but not sure if that is related to this issue. We added `-webkit-user-select: none;` to scenery elements to fix this in https://github.com/phetsims/scenery/issues/1006. Please reassign if I can be of more help!

**Comment by zepumph** [comment]
That is amazing. Thank you for the linked issue! I committed a fix just like the one used for aria live. @BLFiedler can you confirm fixed in this dev version?

https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.16/phet/ratio-and-proportion_en_phet.html

**Comment by BLFiedler** [comment]
It shrunk! But I wonder if the problem is more to do with iPad gesture features? If you hold long enough (just a few seconds while not moving the cursor), a zoom feature appears on the cursor area. I made a quick video to show it off.

https://drive.google.com/open?id=1P08rRfCcH7EyKjBQEgM3GvfiHORW7k3X

It happened rather frequently during that last interview clip I sent yesterday if you get a chance to watch.

**Comment by jessegreenberg** [comment]
Hmm, I confirmed it is still happening too. I tried all of these things but they didn't help, though canvas element is smaller again.

```js
      // disable all pointer events?
      canvas.style.pointerEvents = 'none';

      // invisible selection color?
      canvas.style[ '-webkit-tap-highlight-color' ] = 'rgba(255,255,255,0)';

      // what if it has zero dimensions?
      canvas.width = '0px';
      canvas.height = '0px';

      // prevent default touch behavior?
      canvas.ontouchstart = event => {
        event.preventDefault();
      };

      // maybe if its behind the sim that will help?
      document.body.insertBefore( canvas, document.getElementById( 'sim' ) );
      const ctx = canvas.getContext( '2d' );
```

**Comment by jessegreenberg** [comment]
I noticed that svg elements for text have
```js
      canvas.style.position = 'absolute';
      canvas.style.left = '-65535px';
      canvas.style.right = '-65535px';
```
and setting this on the canvas element seems to fix it.

**Comment by zepumph** [comment]
Thanks so much for diving into this. Do you think we should keep the user-select style too?

**Comment by zepumph** [comment]
After discussing with @jessegreenberg and doing some testing, we decided to keep both. It wasn't clear what was best for all devices. On my iPad I was able to fix the bug with just the "user-select:none"  style, and for @jessegreenberg last night, both seemed to fix it. We will keep both!

@BLFiedler please confirm fixed on phettest.

**Comment by zepumph** [comment]
You can also confirm fixed in https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.17/phet/ratio-and-proportion_en_phet.html

**Comment by BLFiedler** [comment]
You know, it looks fixed to me! Thanks @jessegreenberg & @zepumph!
