### ISSUE TITLE
Some strings are no longer translated

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#515]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/831.
The "Challenge 1," "Challenge 2," "Challenge 3," and "Ratio Lock" strings are no longer translated in any language, even though they may be in the published sim.

**Visuals**
<img width="511" alt="Nottranslate2" src="https://user-images.githubusercontent.com/41024075/189755392-7da1db5d-30e1-45b6-aa9d-3ac077621adb.png">
<img width="508" alt="nottranslate1" src="https://user-images.githubusercontent.com/41024075/189755396-0e30cdbe-7ac4-48d8-8812-f14d31699c7a.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.31/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-dev.31 2022-08-24 16:50:40 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by zepumph** [comment]
This is fixed by https://github.com/phetsims/ratio-and-proportion/issues/499

**Comment by KatieWoe** [comment]
Testing for https://github.com/phetsims/ratio-and-proportion/issues/499. While the Challenge strings are now translated, the Ratio Lock string still isn't. Reopening.

**Comment by zepumph** [comment]
Thanks. I renamed the string key and thought it wouldn't matter. My bad! I brought it back. Thanks for reopening. I appreciate it and apologize that you had to pick up my slack. Closing
